HOST="" #INSERT THE HOST/IP
#AUTHENTICATION

USER="" #INSERT THE USER
PASSWD='' #INSERT THE USER PASSWORD
PATH_SSH="" #INSERT THE SSH PATH WHERE THE KNOW_HOSTS IS LOCATED IN YOUR LOCAL MACHINE

#REMOTE DIRECTORIES

REMOTE_DIR_APPS="" #INSERT THE REMOTE DIRECTORY OF APPS
REMOTE_DIR_KVSTORE=""#INSERT THE REMOTE DIRECTORY OF KVSTORE
REMOTE_DIR_MODINPUTS=""#INSERT THE REMOTE DIRECTORY OF MODINPUTS

#LOCAL DIRECTORIES

LOCAL_DIR_APPS="" #INSERT THE DIR WHERE THE APPS WILL BE STORED
LOCAL_DIR_MODINPUTS="" #INSERT THE DIR WHERE THE MODINPUTS WILL BE STORED
LOCAL_DIR_KVSTORE="" #INSERT THE DIR WHERE THE KVSTORE WILL BE STORED


